version: "3.7"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: sdp-db-pass
      POSTGRES_USER: sdp-user
      POSTGRES_DB: subcontractor-demo-project
