openapi: "3.0.3"
info:
  title: "Subcontractor Demo Project"
  version: 0.0.1
servers:
  - url: http://localhost:7822
paths:
  /subcontractors:
    get:
      tags:
        - subcontractors
      summary: Gets all subscontractors
      responses:
        200:
          description: success
  /projects:
    get:
      tags:
        - projects
      summary: Gets all projects
      responses:
        200:
          description: success
    post:
      tags:
        - projects
      summary: Create a project
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subcontractors:
                  type: array
                  items:
                    type: string
                  example:
                    [
                      5d46b0c7-f754-471a-90b4-a013c45297d0,
                      420e13ac-3f43-4822-859e-b8e5f0257784,
                    ]
                name:
                  type: string
                  example: Test project
                address:
                  type: string
                  example: 1639 Lamberts Branch Road
                city:
                  type: string
                  example: Amelia
                state:
                  type: string
                  example: Ohio
                zipcode:
                  type: string
                  example: 45102
      responses:
        200:
          description: success
  /projects/{id}:
    get:
      tags:
        - projects
      summary: Get a single project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 8d721ed9-ddc0-42d8-8667-d5896d509a66
      responses:
        200:
          description: success
  /draws:
    get:
      tags:
        - draws
      summary: Get all tags
      responses:
        200:
          description: success
    post:
      tags:
        - draws
      summary: Create a draw
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                project:
                  type: string
                  example: 8d721ed9-ddc0-42d8-8667-d5896d509a66
      responses:
        200:
          description: success
  /payrolls:
    get:
      tags:
        - payrolls
      summary: Get all payrolls
      responses:
        200:
          description: success
    post:
      tags:
        - payrolls
      summary: Create a payroll
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                draw:
                  type: string
                  example: ad687297-d3a5-4ff4-bf37-ffe43b011352
                subcontractor:
                  type: string
                  example: 5d46b0c7-f754-471a-90b4-a013c45297d0
      responses:
        200:
          description: success
  /payrolls/{id}:
    patch:
      tags:
        - payrolls
      summary: Update a payroll
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: e15636fa-2913-4e80-bfb8-d399366ac2e6
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: COMPLIANCE_UPLOADED
      responses:
        200:
          description: success
